set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'
Plugin 'Valloric/YouCompleteMe'

call vundle#end()            " required
filetype plugin indent on    " required

syntax enable
set exrc
set background=dark
set secure 
colors hybrid
highlight clear LineNr
set esckeys
set number
set hlsearch
set mouse=a
set nostartofline
set ruler
set showmode
set title

set expandtab
set tabstop=4
set shiftwidth=4
set softtabstop=4 
